### PR TITLE
#3: Tutorial Step 3 (closes #3)

### LINKED ISSUE #3: Tutorial Step 3
Step 3

Use a `Move` model instead of Strings.

Requirements

- convert the user input to a valid Move data type
- use ADT (Algebraic Data Type, i.e. sealed case objects in Scala) encoding for enum (see https://underscore.io/blog/posts/2014/09/03/enumerations.html)
- use an Option to signal the parsing can fail
- refactor the implementation to work with the `Move` data type

### PR DESCRIPTION
**Pull request by MatteoTurri**
Closes #3

### tests performed

Manual testing with valid input (0,1,2) and not valid input (3, 6572, ciao)

### CODE REVIEW

File: src/main/scala/rps/Game.scala [hunk 1]
```diff
@@ -5,44 +5,43 @@ object Game {
     println("Please select your move: input 0 for Rock, 1 for Paper and 2 for Scissors")
     val userInput: String = scala.io.StdIn.readLine();
     val userMove: Option[Move] = matchInput(userInput)
-    val cpuMove: Option[Move] = getCpuMove()
-    println("User move is "+getMoveString(userMove))
-    println("CPU move is "+getMoveString(cpuMove))
-    println(getOutcome(userMove, cpuMove))
+    val cpuMove: Move = getCpuMove()
+    if(userMove.isDefined)
```
Comment (gabro) [inline src/main/scala/rps/Game.scala]: almost! Try using map ;)

File: src/main/scala/rps/Game.scala [hunk 2]
```diff
@@ -3,46 +3,42 @@ package rps
...
-    val userInput = scala.io.StdIn.readInt()
-    val userMove = matchInput(userInput)
-    val cpuMove = getCpuMove()
-    println("User move is "+getMoveString(userMove))
-    println("CPU move is "+getMoveString(cpuMove))
-    println(getOutcome(userMove, cpuMove))
+    val userInput: String = scala.io.StdIn.readLine();
+    val userMove: Option[Move] = matchInput(userInput)
+    val cpuMove: Move = getCpuMove()
+    userMove.map(x => getOutcome(x, cpuMove)).getOrElse(println("User input is not valid"))
```
Comment (gabro) [inline src/main/scala/rps/Game.scala]: nice :)
